### PR TITLE
fix(client): fix ss key parsing for passwords with special characters

### LINKED ISSUE #2419: [Bug]: Legacy base64 encoded keys with special characters in passwords no longer valid
### Application

Outline Client

### Describe the bug

After auto update, all my shadowsocks config dropped. but i can't add any shadowsocks config.
[Bug]: Client app is unable to add VPN access key (shadowsocks)
[Error Messages] invalid access key.

### Steps to reproduce

1. open client [Mac OS or iOS client]
2. click button [add server]
3. paste your ss://key

### What did you expect to happen?

added successfully

### What actually happened?

Error : invalid access key

### Outline Version

Version 1.15.0 (483119)

### What operation system are you using?

macOS

### Operating System Version

13.7.4 (22H420)

### Screenshots and Videos

Image
Image

### PR DESCRIPTION
**Pull request by sbruens**
Fixes #2419.

This covers incorrect parsing of passwords containing special characters in 2 places:
- legacy base64 URIs
- SIP002 unencoded URIs

 This is a regression from when we moved away from using https://github.com/Jigsaw-Code/outline-shadowsocksconfig.

### CODE REVIEW

File: client/go/outline/config/config_shadowsocks.go [hunk 1]
```diff
@@ -275,15 +290,30 @@ func parseShadowsocksSIP002URL(url url.URL) (*ShadowsocksConfig, error) {
...
-	}
-	cipherName, secret, found := strings.Cut(cipherInfo, ":")
-	if !found {
-		return nil, errors.New("invalid cipher info: no ':' separator")
+		// Base64 decoding failed, assume percent encoding.
+		cipherName, secret, found = strings.Cut(userInfo, ":")
+		if !found {
+			return nil, errors.New("invalid cipher info: no ':' separator")
+		}
+		cipherName, err = neturl.QueryUnescape(cipherName)
```
Comment (fortuna) [inline client/go/outline/config/config_shadowsocks.go:309]: Why are you unescaping the cipher name? userinfo should already be unescaped, since it came from url.User.String()

File: client/go/outline/config/config_shadowsocks.go [hunk 2]
```diff
@@ -275,15 +290,30 @@ func parseShadowsocksSIP002URL(url url.URL) (*ShadowsocksConfig, error) {
...
+		if err != nil {
+			return nil, errors.New("cipher not percent encoded")
+		}
+		secret, err = neturl.QueryUnescape(secret)
```
Comment (fortuna) [inline client/go/outline/config/config_shadowsocks.go:313]: Same. This should already be unescaped.

File: client/go/outline/config/config_shadowsocks.go [hunk 3]
```diff
@@ -275,15 +290,30 @@ func parseShadowsocksSIP002URL(url url.URL) (*ShadowsocksConfig, error) {
 		// Try base64 decoding in legacy mode
 		decodedUserInfo, err = base64.StdEncoding.DecodeString(userInfo)
 	}
-	var cipherInfo string
+	var (
```
Comment (fortuna) [inline client/go/outline/config/config_shadowsocks.go:293]: I believe we can revert this function. Do you have an example this change fixes?

File: client/go/outline/config/config_shadowsocks_test.go [hunk 4]
```diff
@@ -33,43 +35,46 @@ func parseFromYAMLText(configText string) (*ShadowsocksConfig, error) {
 }
 
 func TestParseShadowsocksConfig_URL(t *testing.T) {
-	t.Run("Fully Encoded", func(t *testing.T) {
-		encoded := base64.URLEncoding.WithPadding(base64.NoPadding).EncodeToString([]byte("chacha20-ietf-poly1305:SECRET@example.com:1234?prefix=HTTP%2F1.1%20"))
+	t.Run("Fully Base64 Encoded", func(t *testing.T) {
+		encoded := base64.URLEncoding.WithPadding(base64.NoPadding).EncodeToString([]byte("chacha20-ietf-poly1305:SECRET/!@#@example.com:1234?prefix=HTTP%2F1.1%20"))
```
Comment (fortuna) [inline client/go/outline/config/config_shadowsocks_test.go:39]: Can you try an example with `chacha20-ietf-poly1305:SECRET@example.com:80@example.com:1234?prefix=HTTP%2F1.1%20`

File: client/go/outline/config/config_shadowsocks.go [hunk 5]
```diff
@@ -233,26 +245,29 @@ func parseShadowsocksLegacyBase64URL(url url.URL) (*ShadowsocksConfig, error) {
 		// If decoding fails, return the original url with error
 		return nil, fmt.Errorf("failed to decode host string [%v]: %w", url.String(), err)
 	}
+
+	// The decoded URI doesn't follow RFC3986; the password is expected to be plain text.
```
Comment (fortuna) [inline client/go/outline/config/config_shadowsocks.go:249]:
```suggestion
	// The decoded URI doesn't follow RFC3986, so we need our own parsing. The password is expected to be plain text.
```

**Review by fortuna — COMMENTED** [review]
I'm still trying to wrap my head around the fully encoded case. Can you try the example I shared?

File: client/go/outline/config/config_shadowsocks.go (hunk 3 above)
Comment (sbruens) [reply client/go/outline/config/config_shadowsocks.go:293]: We're not parsing non-base64 encoded userinfos properly. It's the counterpart of the legacy URI format for passwords containing special characters. I should update the PR description though since I'm technically fixing the behavior in 2 places.

Example key:

```
ss://chacha20-ietf-poly1305:test%2F!%40%23:@192.168.100.1:8888
```

The password here should be "test/!@#" but it incorrectly parses it as "test%2F%21%40%23%3A". The test case update covers this scenario.

File: client/go/outline/config/config_shadowsocks_test.go (hunk 4 above)
Comment (sbruens) [reply client/go/outline/config/config_shadowsocks_test.go:39]: Added a separate test case for it.

File: client/go/outline/config/config_shadowsocks.go (hunk 1 above)
Comment (sbruens) [reply client/go/outline/config/config_shadowsocks.go]: Ok yes I should use those instead of the string. I should have looked at the `UserInfo` type more closely.

**Review by fortuna — COMMENTED** [review]
I see your latest changes. I think the only outstanding issue is figure out what to do with `chacha20-ietf-poly1305:SECRET/!@#@example.com:1234?prefix=@bad.example.com:443` in the legacy fully escaped format. It's ambiguous!
Should we forbid query params in the legacy format?

**Comment by sbruens** [comment]
Instead of fully blocking question marks, I instead opted to check if there is an ambiguity in parsing (i.e. there are query strings in both). Let me know if this is too convoluted though and we could just block the existence of `?` only. Added a bunch of test cases that should illustrate what is and isn't allowed. Lmk what you think.

File: client/go/outline/config/config_shadowsocks_test.go [hunk 6]
```diff
@@ -33,43 +35,131 @@ func parseFromYAMLText(configText string) (*ShadowsocksConfig, error) {
...
+	})
+
+	t.Run("Fully Base64 Encoded Having Query Parameters With Password", func(t *testing.T) {
+		tests := []struct {
+			name    string
+			input   string
+			wantErr bool
+		}{
+			{
+				name:    "Ambiguous Query Parameter",
```
Comment (fortuna) [inline client/go/outline/config/config_shadowsocks_test.go:65]: None of these are actually ambiguous, because the first `@` is not followed by a hostname, or there's only one `@`. They can all only be parsed one way really.

Please add the ambiguous example I shared as that one will actually parse successfully in two different ways.

File: client/go/outline/config/config_shadowsocks.go [hunk 7]
```diff
@@ -233,26 +245,37 @@ func parseShadowsocksLegacyBase64URL(url url.URL) (*ShadowsocksConfig, error) {
...
-		return nil, fmt.Errorf("invalid user info: %w", err)
-	}
-	cipherInfoBytes := newURL.User.String()
-	cipherName, secret, found := strings.Cut(string(cipherInfoBytes), ":")
-	if !found {
-		return nil, errors.New("invalid cipher info: no ':' separator")
+
+	// Check if both the secret and the host have query parameters. Parsing keys containing both can
+	// be ambiguous, so we disallow it altogether to avoid surprises.
+	if strings.Contains(secret, "?") && newURL.RawQuery != "" {
```
Comment (fortuna) [inline client/go/outline/config/config_shadowsocks.go:273]: It's not quite clear to me that this solves the ambiguity.

Perhaps we should determine that we will be greedy and always get the last `@` to determine the host name. Then people can url-encode the `@` in the query if needed.

Comment (fortuna) [reply client/go/outline/config/config_shadowsocks.go]: I agree with this getting too complicated. Yes, the greedy approach is what I am suggesting

**Review by fortuna — APPROVED** [review]
Looks great. Thanks!
